name: Bug Report
description: File a bug report
title: "[BUG REPORT]: "
labels: [bug]
assignees:
  - 1Danish-00
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: os
    attributes:
        label: Your System?
    validations:
      required: true
  - type: dropdown
    id: pyversion
    attributes:
      label: Python Version
      description: Your Python version?
      options:
        - latest
        - 3.9
        - 3.8
        - 3.7
        - 3.6 
        - 3.5
        - 3.x
        - 2.x
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: HtmlWebShot Version
      description: Which version of htmlwebshot are you using?
      options:
        - latest
        - v0.1.1
        - v0.1
        - pre-release
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug!"
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Used Code.
      description: Paste Your Code Here
      render: python
  - type: textarea
    id: error
    attributes:
      label: Error Logs.
      description: Paste Your Errors
      render: shell
